### ISSUE TITLE
Make public AppendUnitOfMeasure

### ISSUE THREAD

**Issue by kostazol** [nick-buhro/NumToWords#3]
Hello. Can you change Access Modifier for the AppendUnitOfMeasure method? Or can you create public method to convert only measure?

**Comment by nick-buhro** [comment]
Hello, I've just added `UnitOfMeasure.GetForm(long number)` in #5, so you can use it to convert only measure.

**Comment by kostazol** [comment]
**Thanks you!** And other thanks you for changing the target platform to .NET Standart 2.0!
